### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str' in playlist.py

### ISSUE THREAD

**Issue by c02y** [electronut/pp#13]
My python: v3.6.1

`python playlist.py --dup test-data/rating.xml `

output:

    ...
    TypeError: a bytes-like object is required, not 'str'

in `findDuplicates()`, changing

        f = open("dups.txt", 'wb')

to

        f = open("dups.txt", 'w')

will fix it.

**Comment by electronut** [comment]
Fixed, thanks.
