### ISSUE TITLE
small error in laser.py

### ISSUE THREAD

**Issue by harikrishnavasala** [electronut/pp#17]
hi sir,i executed laser.py in windows in a cmd but when i given --port COM3 executed.
 but ,small error saying 
AttributeError:'module' object as no attrubute 'Serial'

**Comment by harikrishnavasala** [comment]
@electronut i imported serial module but in execution it saying

 AttributeError:'module' object as no attrubute 'Serial

**Comment by electronut** [comment]
Please see the book Appendix for required python module installation. You probably don't have pyserial installed.
