### ISSUE TITLE
No module named glutils

### ISSUE THREAD

**Issue by quakig** [electronut/pp#6]
Ref to code in folder `volrender`

The files `raycast.py`, `raycube.py`, `slicerender.py`  import another module called `glutils` but the module is no where found in the code.

Thanks the book has been an engrossing read so far !

**Comment by electronut** [comment]
glutils is in https://github.com/electronut/pp/tree/master/common

You have to add the folder to your PYTHONPATH . (It's mentioned in the beginning of Appendix A.)

Glad you like the book!
