### ISSUE TITLE
b'invalid operation' in volrender.py

### ISSUE THREAD

**Issue by patmo141** [electronut/pp#8]
I'm attempting to work through the Volume Rendering chapter.  Love the book!  This may be a driver or system error but any tips for teasing out this error would be greatly appreciated!

1.  I'm using windows7 64 bit and python 3.4 64bit (I made sure with platform.architecture())
2.  I downloaded the 64bit glfw binaries from http://www.glfw.org/download.html
3.  I copied glfw3.dll from the libvc-2012 folder into volrender.py and hardcoded the path to the dll in volrender.py.  That seems to be working because glfw.glfwInit() returns 1
4.  I get "invalid operation' error when it get to the glViewport() call.

![image](https://cloud.githubusercontent.com/assets/2917743/14415349/1d8a6cd4-ff6c-11e5-9177-bda5f9437aad.png)

**Comment by electronut** [comment]
Hello,

Thanks for buying the book!

Regarding your error, a few questions/suggestions:

1. Are you able to run the first OpenGL project in chapter 9?

   https://github.com/electronut/pp/tree/master/simplegl

2. Instead of copying the dll and hardcoding paths, could you follow the process outlined in Appendix A, page 298?  (See image below.)

The error indicates that the OpenGL context is invalid, which could be due to a number of reasons, but let's try to get the chapter 9 code to work first. 

<img width="384" alt="screen shot 2016-04-11 at 9 04 50 am" src="https://cloud.githubusercontent.com/assets/3272706/14416173/b903e41c-ffc4-11e5-9256-77d49375deb7.png">

**Comment by patmo141** [comment]
Re ch9:  You have caught me!  Trying to run before I walk.  Yes I will try this first.

Re PATH:  Yes that's no problem, it was just laziness on my part.

It will probably be sometime toward end of week.  Thanks, Patrick

**Comment by electronut** [comment]
Sure. Let me know if you need help.

**Comment by patmo141** [comment]
Ok, couldn't resist playing some more.

1.  I set up my PYTHONPATH and GLFW_LIBRARY environment variables
2.  I read (ok, I read part of and skimmed all of) Ch. 9
3.  I ran simpleglfw.py and....

![image](https://cloud.githubusercontent.com/assets/2917743/14446773/6e88b3a0-0027-11e6-9f40-a04d57b3f88f.png)

More information to come

**Comment by electronut** [comment]
Could you try this quick test:

```
 > cd c:\dev\...\simplegl
 > python simpleglfw.py

```
Just wondering it it's still a path issue.

**Comment by patmo141** [comment]
![image](https://cloud.githubusercontent.com/assets/2917743/14447076/749bf0e2-002a-11e6-89f2-ea31158feb33.png)

I have multiple python versions so I did a slightly different by explicity pointing to python34 since that is where my OpenGL is installed in site-packages.

**Comment by electronut** [comment]
I am bit stumped...

How about the official glfw example below. Can you try running it?

https://pypi.python.org/pypi/glfw

If you can't run the above, one guess would be that your OS doesn't have an OpenGL driver installed. Could you try installing a driver for your graphics card? If you send me the system details, I can try to help.

**Comment by patmo141** [comment]
While I am getting driver's updated.  I have one of those dual graphics card situations, where the builtin chip operates some times, and the dedicated GPU works others.

![image](https://cloud.githubusercontent.com/assets/2917743/14471350/2ccee5b6-00bc-11e6-8c32-8a4ed711b699.png)

**Comment by electronut** [comment]
Any luck with the official glfw example?

**Comment by patmo141** [comment]
was able to run hello world gflw example from https://pypi.python.org/pypi/glfw
I downloaded glfw.py from https://github.com/FlorianRhiem/pyGLFW
I had to hardcode the location of glfw3.dll in that example because it could not find it even with the envorinment variable set, however once I did that, all was well

![image](https://cloud.githubusercontent.com/assets/2917743/14479361/9516ee32-00eb-11e6-86c4-e005ec8208aa.png)

**Comment by electronut** [comment]
So if the official glfw sample works, glsimple.py should work?

**Comment by patmo141** [comment]
The bindings are all different in the github version https://github.com/FlorianRhiem/pyGLFW/blob/master/glfw.py  For example glfw.init() vs glfw.glfwInit().  I will alter them and see if I can get glsimple.py to work if I change the bindings.

**Comment by patmo141** [comment]
Ok, I changed all the functions in simpleglfw.py to match the glfw.py bindings from github, and I get the same error 'invalid operation', so I must have an issue with OpenGL drivers or PyOpenGL

**Comment by electronut** [comment]
Can we go back to the glfw example:

https://pypi.python.org/pypi/glfw

Do NOT use https://github.com/FlorianRhiem/pyGLFW

You should be using glfw.py from the common/ directory of the book's source code.

Can you send me your PYTHONPATH?

**Comment by patmo141** [comment]
the example code from pypi.python.org will not work with pp-master/common/glfw.py  because the bindings are defined differently (eg, CamelCase vs lower_case).

My PYTHONPATH is only "C:\Dev\pp-master\common"  I do the majority of my work in Blender python so I have not added anything to PYTHONPATH except this project :-)

**Comment by patmo141** [comment]
I am starting fresh, updating drivers, installing PyOpenGL from PyPi, downloading fresh pp-master source to eliminate any setup errors on my part.  Thanks for all of your help so far!  I'll report back shortly

**Comment by patmo141** [comment]
Step 1.  Fresh pp-master directory
Step 2. PYTHONPATH: "C:\Dev\pp-master\common", 
Step 3. GLFW_LIBRARY "C\Dev\glfw\lib-vc2012\glfw3.dll
Step 4.  Modify the example from PyPi to match the functions in C:\Dev\pp-master\common\glfw.py

`import glfw

def main():
    # Initialize the library
    if not glfw.glfwInit():
        return
    # Create a windowed mode window and its OpenGL context
    window = glfw.glfwCreateWindow(640, 480)
    if not window:
        print('failed to open window')
        glfw.glfwTerminate()
        return
    # Make the window's context current
    glfw.glfwMakeContextCurrent(window)

    # Loop until the user closes the window
    while not glfw.glfwWindowShouldClose(window):
        # Render here, e.g. using pyOpenGL

        # Swap front and back buffers
        glfw.glfwSwapBuffers(window)

        # Poll for and process events
        glfw.glfwPollEvents()

    glfw.glfwTerminate()

if __name__ == "__main__":
    main()`

**Comment by patmo141** [comment]
So, hours and hours ago, I tried global settings to test Nvida card and Builtin Intel card.  Apparently it was ignoring my settings because once I specified that Python uses the Nvidia card, it works.

![image](https://cloud.githubusercontent.com/assets/2917743/14481781/3b99c44c-0104-11e6-85ca-9948626506ae.png)

**Comment by electronut** [comment]
Awesome. Glad to see it working!

**Comment by patmo141** [comment]
Me too.  I'm sorry I hope I did not waste too much of your time.  And for final closure

![image](https://cloud.githubusercontent.com/assets/2917743/14481963/af98f786-0105-11e6-9432-a0c65a183b11.png)

**Comment by electronut** [comment]
Happy to help!

A request:

If you like the book, please take a few minutes to write a review on amazon.com:

http://www.amazon.com/Python-Playground-Projects-Curious-Programmer/dp/1593276044
